---
- name: Fetch data from a public API and display it
  hosts: all
  tasks:
    - name: Make a GET request to a public API
      uri:
        url: https://jsonplaceholder.typicode.com/posts
        method: GET
        return_content: yes
      register: api_response

    - name: Display API response in logs
      debug:
        msg: "{{ api_response.json }}"
