---
- name: Fetch data from a public API and display it with flair
  hosts: all
  tasks:
    - name: Make a GET request to a public API
      uri:
        url: https://jsonplaceholder.typicode.com/posts
        method: GET
        return_content: yes
      register: api_response

    - name: Display formatted API response with flair
      debug:
        msg: |
          **API Response (JSONPlaceholder)**
          ============================================
          Status Code: {{ api_response.status }}
          ============================================
          Response Length: {{ api_response.content | length }} bytes
          ============================================
          Sample Data:
          {% for post in api_response.json[:3] %}
          - Post ID: {{ post.id }} | Title: {{ post.title }}
          {% endfor %}
          ============================================
          Total Posts: {{ api_response.json | length }}
          ============================================
          [Note: Logs are formatted with flair for visibility]
      verbosity: 1
