---
- name: Fetch data from a public API and display a random message
  hosts: localhost
  tasks:

    # Define a list of random messages
    - name: Define a list of random messages
      set_fact:
        messages:
          - "Hello, world!"
          - "Ansible is awesome!"
          - "Debugging rocks!"
          - "Random message!"
      
    # Choose a random message
    - name: Choose a random message
      set_fact:
        random_message: "{{ messages | random }}"

    # Display the random message
    - name: Display the random message
      debug:
        msg: "{{ random_message }}"
