---
- name: Fetch data from a public API and display a random message Second time
  hosts: localhost
  tasks:
    # Define a list of random messages
    - name: Define a list of random messages
      set_fact:
        messages:
          - "Second message, Hello, world!"
          - "Second message, Ansible is awesome!"
          - "Second message, Debugging rocks!"
          - "Second message, Random message!"
      
    # Choose a random message
    - name: Choose a random message
      set_fact:
        random_message: "{{ messages | random }}"

    # Display the random message
    - name: Display the random message
      debug:
        msg: "{{ random_message }}"
